version: '3.8'

services:
  webfinger:
    image: williamcook/webfinger:latest
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      GIN_MODE: $GIN_MODE