apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webfinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-webfinger
  template:
    metadata:
      labels:
        app: go-webfinger
    spec:
      containers:
      - name: go-webfinger
        image: williamcook/webfinger:latest
        ports:
        - containerPort: 8080

